### ISSUE TITLE
Seems that the google docs template is down

### ISSUE THREAD

**Issue by madcsaba** [NUKnightLab/timeline-addon#3]
The Official TimelineJS3 Template on google drive https://drive.google.com/previewtemplate?id=1pHBvXN7nmGkiG8uQSUB82eNlnL8xHu6kydzH_-eguHQ&mode=public
 is not working, when it's copy's url address is tested to preview a timeline through it's data at here:
http://timeline.knightlab.com/docs/using-spreadsheets.html

**Comment by madcsaba** [comment]
Is there anything with that? It is not working

**Comment by JoeGermuska** [comment]
I'm having trouble understanding your question. It doesn't seem to be about the Google Sheets "Add on," so this is probably not the best place to seek help. I'll answer anyway, but will close this issue as well.

It sounds as though you are trying to use the first URL in your message above as the URL of a spreadsheet. This is not how it is meant to be used. Instead, click the button at the top which says "use this template." That creates a usable spreadsheet. You would still need to go through ["step 2"](http://timeline.knightlab.com/#make-step-2) from the authoring instructions to "publish to the web."

![image](https://cloud.githubusercontent.com/assets/46313/18274801/e7ddd9c8-7409-11e6-9d0a-28e275fff171.png)
